### ISSUE TITLE
Feature tracking

### ISSUE THREAD

**Issue by kungpaogao** [kungpaogao/flux-rewrite#2]
This was previously on my personal Notion, but it makes more sense to put it here.

- [x]  recyclerview click
- [x]  networking
    - [x]  firebase auth
    - [x]  fetching data
    - [x]  serializing data
    - [x]  use coroutines
    - [x]  menus
    - [x]  hours
- [ ]  actual ui
    - [x]  list cards
    - [x]  collapsing scroll view with search
    - [x]  campus location filters
        - [x]  actual functions
    - [x]  dining detail page
        - [x]  menu tabs
        - [x]  menus
        - [x]  day chips - do this last, breaks preview
        - [ ]  feedback link + dialog
        - [x]  facility hours
        - [x]  last updated
        - [x]  no menu text
        - [x]  disable scroll inside viewpager recycler view
    - [x]  app bar actions
        - [x]  navigation up
        - [x]  refresh
            - [ ]  limit refresh to every minute
            - [x]  show spinner
        - [x]  dining list sorting order
        - [x]  search bar
        - [x]  swipe to refresh
    - [ ]  typography - colors, sizes
    - [x]  progress bars/loading ui
        - [x]  loading/refreshing states
        - [x]  toast message/snackbar on update
        - [x]  initial splash screen/anim while loading facility list
            - [ ]  only show on first run
    - [ ]  error handling + screens
    - [x]  BUG: rotating screen crashes app
- [x]  set app icons
- [ ]  dx: repository linting — force on commit/PR
- [ ]  unsubscribe from click listeners??
- [ ]  bonus: repository/caching - storing network data - maybe not for now
- [x]  github actions
